### PR TITLE
This should fix impetus connections disconnecting on world load

### LINKED ISSUE #275: Impetus Links Not Working Correctly
Every once in a while, the links between the Impetus Drainer, Relay, and Matrix will just... break. After a while, the links disappear, and when I try to re-link everything, the charged Impetus does not transfer. In fact, with Impetus already in the Matrix, the Impetus will not transfer even when linked to the Diffuser or the Void Recharge Pedestal,

This seems to occur when I am not around the links to keep them loaded all the time; I have not seen it occur while I have been around the links when they work properly. I tried to solve this by using an Extra Utilities 2 Chunk Loader to keep a 3x3 chunk area loaded, but to no success.

### PR DESCRIPTION
**Pull request by Srdjan-V**
The problem is that the blocks in another chunk might not be loaded by the time this function is called, but eater way you are validating the links once the tile starts ticking. This fix might not be perfect, as i have only tested the impetus gates, drainer and generators

Should fix  #275

### CODE REVIEW

**Comment by TheCodex6824** [comment]
The reason I had that check in the first place was so that impetus nodes didn't become chunkloaders - otherwise, as long as 1 node in a network was loaded naturally, the entire thing would be loaded as it loads the network. I don't think removing that is the best option, given that could probably be used for nefarious things.

That being said, since you figured out the actual cause of the problem (and thank you for doing that, I could never get it to happen for me), we can think of other solutions. From what I can tell, the issue seems to be that `addInput` / `addOutput` never get called if the linked node is not loaded at the time `initClient` / `initServer` is called. Since the position is still in the node's location sets, all that really needs to be done to fix it is to tell the node to try connecting to the node again (the same way as in `initClient` / `initServer`).

The place to do that would probably be in `NodeHelper#validateOutputs`, since that already gets called every so often. If you want to try that, you would need to loop over the **output locations** of the node and check if they are in the same graph. If they aren't, try to add them similarly to in `initClient` / `initServer`. The only difference would be that instead of just having an `addOutput` call if the node is loaded, you would also need to do a corresponding `addInput` on the new node, since there is no init code that will eventually call it for you.

If you want to try that feel free - or if I got something wrong / you have a better idea, please let me know. Thanks again for figuring this out though - I tried so many different ways to try to get chunks to not load between connections so I could test it, but it seems like this case didn't want to happen for me for whatever reason.

**Review by TheCodex6824 — CHANGES_REQUESTED** [review]
See discussion in comment above regarding chunkloading concerns

**Comment by Srdjan-V** [comment]
The problem was that debugging such a scenario is difficult, the requirement to trigger this is a extremely high load on the world(low end hardware or a highly modded instance).

The chunk loading problem should be a easy fix, with all the information you have provided. I will still need some time to fully understand your code, but that should not be difficult.

**Comment by Srdjan-V** [comment]
I have formatted the files i worked on, i hope that that is not a problem. And also added a option to download source code and javadoc

I have not tested this on my instance, i will probably do it tomorrow.

File: src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java [hunk 1]
```diff
@@ -149,219 +149,252 @@ public boolean removeOutput(IImpetusNode output) {
...
+        return true;
+    }
+
+    private boolean validateNodeInput(World world, DimensionalBlockPos pos) {
+        if (world.provider.getDimension() == pos.getDimension()) {
+            TileEntity te = world.getTileEntity(pos.getPos());
+            if (te != null) {
+                IImpetusNode possible = te.getCapability(CapabilityImpetusNode.IMPETUS_NODE, null);
+                if (possible != null) {
+                    if (world.isBlockLoaded(pos.getPos())) {
```
Comment (TheCodex6824) [inline src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java:304]: Move the `world.isBlockLoaded` check before getting the `TileEntity` - getting a `TileEntity` can load chunks, so getting it first means the check doesn't really do anything.

File: src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java [hunk 2]
```diff
@@ -149,219 +149,252 @@ public boolean removeOutput(IImpetusNode output) {
...
+        return false;
+    }
+
+    private boolean validateNodeOutput(World world, DimensionalBlockPos pos) {
+        if (world.provider.getDimension() == pos.getDimension()) {
+            TileEntity te = world.getTileEntity(pos.getPos());
+            if (te != null) {
+                IImpetusNode possible = te.getCapability(CapabilityImpetusNode.IMPETUS_NODE, null);
+                if (possible != null) {
+                    if (world.isBlockLoaded(pos.getPos())) {
```
Comment (TheCodex6824) [inline src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java:324]: Same thing here with load check ordering

File: src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java [hunk 3]
```diff
@@ -149,219 +149,252 @@ public boolean removeOutput(IImpetusNode output) {
...
             removeOutput(node);
-        
+
         unload();
     }
-    
-    protected void initServer() {
+
+    @Override
+    public boolean hasUnloadedNodes(World world) {
```
Comment (TheCodex6824) [inline src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java:273]: This method seems to do more than just returning if there are unloaded nodes - you can have a function returning `hasUnloadedNodes`, but maybe split the logic for actually checking / trying to load them into a `tryConnectUnloadedNodes` method or something like that.

Alternatively, you could put that logic into `NodeHelper` (substituting field access with the getters). I'm not sure which one would be a better place for it.

**Review by TheCodex6824 — CHANGES_REQUESTED** [review]
Formatting is fine, as are the javadoc and source downloads.

File: src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java [hunk 4]
```diff
@@ -149,219 +149,272 @@ public boolean removeOutput(IImpetusNode output) {
...
+
+        List<Boolean> checks = new ArrayList<>();
         for (DimensionalBlockPos pos : inputs) {
-            World world = DimensionManager.getWorld(pos.getDimension());
-            if (world != null && world.provider.getDimension() == pos.getDimension() && world.isBlockLoaded(pos.getPos())) {
-                TileEntity te = world.getTileEntity(pos.getPos());
-                if (te != null) {
-                    IImpetusNode possible = te.getCapability(CapabilityImpetusNode.IMPETUS_NODE, null);
-                    if (possible != null)
+            checks.add(validateNodeInput(world, pos, invalid));
```
Comment (TheCodex6824) [inline src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java:282]: Instead of using a list, you can do some boolean operations to get the result:
```
boolean someNodeInvalid = false;
for (...)
    someNodeInvalid |= !validateNodeInput(...);
```
Negating the validate results makes `true` mean that a node is invalid, and `or`-ing them together will result in `true` if at least one invalid result occurred.

File: src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java (hunk 3 above)
Comment (Srdjan-V) [reply src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java:273]: I think that this is a better place as if I would move it I would need to add more methods to the interface, and those methods wouldn't be all that useful.

File: src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java (hunk 4 above)
Comment (Srdjan-V) [reply src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/prefab/ImpetusNode.java:282]: I totally forgot that this exists

**Comment by TheCodex6824** [comment]
Looks good, but there are a few more complex issues I thought of while looking over it (make sure to read the second point before working on things):

1. The world passed to `tryConnectUnloadedNodes` might not be the world the input/output is in. An example would be having impetus mirrors in different dimensions. This already only gets called on the server (since `validateOutputs` is only ran on the server), so the easiest way to fix that is to remove the world argument and use `DimensionManager` to try to get the world like `initServer` does.
2. Since this logic only runs on the server, in a multiplayer scenario it is possible for the server to reconnect nodes but the client to never know that they were reconnected. This means the connection has to be synchronized to the client. I also don't really want concrete sync code to be in `ImpetusNode` as that is meant to be extended by other mods, and I don't want to put what boils down to sending a TA packet in something other mods might use without knowing that is occurring. I feel bad because you already worked on adding things to the interface, but the cleanest way to do all of that might be to move the `tryConnectUnloadedNodes` logic into `NodeHelper` and remove the interface changes. You can substitute the `hasUnloadedNodes` boolean on the node with a check of `node.getInputLocations().size() != node.getInputs().size()` - if the node has more locations than actual node connections, that means at least 1 is unloaded.

I know those changes might be a bit invasive / time consuming, so if you don't have time to do that I can help with it. I apologize for not stopping you earlier, but I completely forgot about the sync aspect since up to this point it "just worked" in `NodeHelper`.

At some point I also need to write better docs for all of the API stuff, because the differences between things like `getInputs` and `getInputLocations` should probably be explained better.

**Comment by Srdjan-V** [comment]
Its not a problem relay, i will get to it once i get the time and if i got any questions i will leave them here

**Comment by Srdjan-V** [comment]
I have a question, what should be validated `getInputLocations()` and `getOutputLocations()` or is `getOutputLocations()` enough. The tile is ticking my the time this method is called so every leaded node should have called by that time, but im not sure if that would compete the loop, i don't know if they are linked. Also that method in `NodeHelper` is called `validateOutputs`, if i have to validate everything should i just make a new method?

**Comment by TheCodex6824** [comment]
> I have a question, what should be validated getInputLocations() and getOutputLocations() or is getOutputLocations() enough.

Good question. Just validating outputs should be enough, as setting the output will also set the corresponding input on the other node. Syncing will work the same way as long as the packet makes it to the client.

Since it's just outputs I also don't think a new method is needed. Normally I would say splitting up functionality into multiple methods is a good idea, but doing that here would require every tile to add another method call, and I think checking unloaded outputs is something that would reasonably be done when validating outputs.

**Comment by Srdjan-V** [comment]
This should be all

File: src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/NodeHelper.java [hunk 5]
```diff
@@ -239,26 +233,46 @@ public static void validateFullGraph(IImpetusGraph graph) {
...
+
+            //Tries to reconnect unloaded nodes
+            for (DimensionalBlockPos pos : node.getOutputLocations()) {
+                World world = DimensionManager.getWorld(pos.getDimension());
+                if (world.provider.getDimension() == pos.getDimension() && world.isBlockLoaded(pos.getPos())) {
+                    TileEntity te = world.getTileEntity(pos.getPos());
+                    if (te != null) {
+                        IImpetusNode possible = te.getCapability(CapabilityImpetusNode.IMPETUS_NODE, null);
+                        if (possible != null) {
+                            node.addInput(possible);
```
Comment (TheCodex6824) [inline src/main/java/thecodex6824/thaumicaugmentation/api/impetus/node/NodeHelper.java:252]: Shouldn't this be `node.addOutput`?

**Review by TheCodex6824 — CHANGES_REQUESTED** [review]
Just the one line and then it's good to go

**Review by TheCodex6824 — APPROVED** [review]
Thanks! I"ll do some testing to make sure everything is good with old worlds and then merge this
